# Generated by Django 5.2.8 on 2025-11-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Названые группы')),
                ('course', models.PositiveSmallIntegerField(choices=[(1, '1-курс'), (2, '2-курс'), (3, '3-курс'), (4, '4-курс'), (5, '5-курс'), (6, '6-курс')], verbose_name='Курс')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.faculty', verbose_name='Факультет')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Студенческая группа',
                'verbose_name_plural': 'Студенческие группы',
                'ordering': ('faculty', 'course', 'name'),
            },
        ),
    ]
